import reactPlugin from "@vitejs/plugin-react";
import { defineConfig } from "vite";
import checkerPlugin from "vite-plugin-checker";
import prettyModuleClassnamesPlugin from "vite-plugin-pretty-module-classnames";
import sassDtsPlugin from "vite-plugin-sass-dts";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    reactPlugin(),
    checkerPlugin({
      typescript: {
        buildMode: true,
        tsconfigPath: "./tsconfig.build.json",
      },
    }),
    prettyModuleClassnamesPlugin(),
    sassDtsPlugin({
      // By default only the `development` mode is enabled, which means that the `d.ts` files are generated only:
      //  - when the `dev` command is running
      //  - and after the source files are changed
      // Let's add the `production` mode so that the `d.ts` files are generated by the `build` command as well.
      enabledMode: ["development", "production"],
      esmExport: true,
    }),
  ],
});
